/*
 *  Name: Spencer Hubbard
 *  Date: 5/7/15
 *  CS 362 Assignment 3
 *
 *  This is a random test generator for the adventurer card. The input for each
 *  test is generated by picking random kingdom cards and two copper cards and
 *  then spliting these cards between the deck and discard. Note that the
 *  randomly picked cards may be split so that one of the deck or discard
 *  contains all of the cards and the other contains none of the cards. The
 *  output checked by each test is the number of coins. Since there are only
 *  two copper in the deck and discard, it follows that both copper cards must
 *  be added to the hand when the adventure card is played. This means that the
 *  number of coins after the card is played should be equal to the sum of two
 *  and the number of coins before the card is played.
 */

#include <stddef.h>  // for NULL, size_t
#include <stdbool.h> // for bool
#include <stdio.h>   // for printf()
#include <stdlib.h>  // for malloc(), free(), exit(), rand(), srand()

#include "dominion.h"
#include "rngs.h"
#include "CS362.h"

#define RANDOM_SEED 42
#define MAX_TESTS 100
#define MIN_PLAYERS 2
#define NUM_TREASURE 2

static int kingdom_cards[10] = {adventurer, council_room, feast, gardens, mine,
    remodel, smithy, village, baron, great_hall};

// Fills given collection of cards with kingdom cards and inserts coppers at random positions
static void helper(int cards[], int numCard, int numTreasure);

static void helper(int cards[], int numCard, int numTreasure) {
  if (numCard > 0) {
    // fill with kingdom cards
    for (int i = 0; i < numCard; i++) {
      cards[i] = kingdom_cards[rand() % 10];
    }
    // place treasure cards
    for (int i = 0; i < numTreasure; i++) {
      cards[rand() % numCard] = copper;
    }
  }
}

int main(int argc, char **argv) {
  srand(RANDOM_SEED);
  
  for (int i = 0; i < MAX_TESTS; i++) {
    // initial setup
    struct gameState state;
    int randomSeed = rand();
    int numPlayers = rand() % (MAX_PLAYERS - MIN_PLAYERS + 1) + MIN_PLAYERS;
    initializeGame(numPlayers, kingdom_cards, randomSeed, &state);
    int whoseTurn = state.whoseTurn;

    // make sure phase = 0, numActions > 0, handCount > 0
    state.phase = 0;
    state.numActions = state.numActions > 0 ? state.numActions : 1;
    state.handCount[whoseTurn] = state.handCount[whoseTurn] > 0 ? state.handCount[whoseTurn] : 1;
    state.hand[whoseTurn][0] = adventurer;

    // pick random number of cards and split cards between deck and discard
    int numCard = rand() % (MAX_DECK - NUM_TREASURE + 1) + NUM_TREASURE;
    int splitTreasure = rand() % (NUM_TREASURE + 1);
    int splitCard = rand() % (numCard - splitTreasure + 1) + splitTreasure;
    state.deckCount[whoseTurn] = splitCard;
    state.discardCount[whoseTurn] = numCard - splitCard;
    helper(state.deck[whoseTurn], state.deckCount[whoseTurn], splitTreasure);
    helper(state.discard[whoseTurn], state.discardCount[whoseTurn], NUM_TREASURE - splitTreasure);
    
    // expected state after test
    int coins = state.coins + NUM_TREASURE;

    // should shuffle deck and discard if < 2 treasure cards are revealed before
    // deck is empty
    // don't check return value of playCard because not unit test for playCard
    playCard(0, 0, 0, 0, &state);

    // test state after card effect
    Verify362(whoseTurn == state.whoseTurn);
    Verify362(coins == state.coins);
  }

  printf("random test for adventure card passed\n");

  return EXIT_SUCCESS;
}
